version: '3.8'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8923
      - FIRESTORE_PROJECT_ID=demo-project
      - FIRESTORE_COLLECTION=items
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge