name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  IMAGE: ${{ secrets.GCP_IMAGE }}
  REGION: ${{ secrets.GCP_REGION }}
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build
        env:
          # Compose full image tag to avoid invalid reference formats and make it easier to debug
          FULL_TAG: "asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE }}:${{ env.TAG }}"
        run: |
          echo "Building image: $FULL_TAG"
          docker build --platform linux/amd64 -f Dockerfile.prod -t "$FULL_TAG" .

      - name: Push
        run: |
          echo "Pushing image: $FULL_TAG"
          docker push "$FULL_TAG"

      - name: Deploy
        run: |
          echo "Deploying service: $SERVICE_NAME with image $FULL_TAG"
          gcloud run deploy "$SERVICE_NAME" --image "$FULL_TAG" --platform managed --region "$REGION" --allow-unauthenticated
