name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: koyofes2025
  SERVICE_NAME: koyofes-check-in-service        # Cloud Run サービス名
  IMAGE_NAME: check-in-service                     # Docker イメージ名（任意で決める）
  REGION: asia-northeast2
  REPOSITORY: cloud-run-source-deploy             # Artifact Registry のリポジトリ名
  FIRESTORE_COLLECTION: visitors
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set FULL_TAG
        run: |
          echo "FULL_TAG=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${TAG}" >> $GITHUB_ENV

      - name: Build
        run: |
          echo "Building image: $FULL_TAG"
          docker build --platform linux/amd64 -f backend/Dockerfile -t "$FULL_TAG" backend/

      - name: Push
        run: |
          echo "Pushing image: $FULL_TAG"
          docker push "$FULL_TAG"

      - name: Deploy
        run: |
          echo "Deploying service: $SERVICE_NAME with image $FULL_TAG"
          gcloud run deploy "$SERVICE_NAME" \
            --image "$FULL_TAG" \
            --platform managed \
            --region "$REGION" \
            --allow-unauthenticated \
            --set-env-vars FIRESTORE_PROJECT_ID=${PROJECT_ID},FIRESTORE_COLLECTION=${FIRESTORE_COLLECTION}
